@startuml
class Shop
class Product
class Customer
class Basket

Shop "1" *-- "*" Product : has
Shop "1" *-- "*" Customer : has
Customer "1" *-- "1" Basket : has
Basket "1" *-- "*" Product : has

Shop : ArrayList<Product> products
Shop : ArrayList<Customer> customers
Shop : displayProducts()

Customer : String userName
Customer : String id
Customer : toString()

Product : String productName
Product : buyProduct()

@enduml